#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("WeatherWidget.Resource", IsApplication=true)]

namespace WeatherWidget
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int star_logo = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int widget_bg = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int widget_bg_normal = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int widget_bg_pressed = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int widget_bg_selected = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070008
			public const int imageView1 = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int imageView2 = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int imageView3 = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int imageView4 = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int imageView5 = 2131165196;
			
			// aapt resource value: 0x7f070007
			public const int linearLayout1 = 2131165191;
			
			// aapt resource value: 0x7f07000d
			public const int linearLayout2 = 2131165197;
			
			// aapt resource value: 0x7f070001
			public const int message = 2131165185;
			
			// aapt resource value: 0x7f07000e
			public const int textView1 = 2131165198;
			
			// aapt resource value: 0x7f070006
			public const int textView10 = 2131165190;
			
			// aapt resource value: 0x7f07000f
			public const int textView2 = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int textView3 = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int textView4 = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int textView5 = 2131165202;
			
			// aapt resource value: 0x7f070002
			public const int textView6 = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int textView7 = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int textView8 = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int textView9 = 2131165189;
			
			// aapt resource value: 0x7f070000
			public const int widget = 2131165184;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int widget_message = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int widget_word = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int widget_loading = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int widget_name = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int BulletPoint = 2131099649;
			
			// aapt resource value: 0x7f060007
			public const int Divider = 2131099655;
			
			// aapt resource value: 0x7f060002
			public const int Text = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int Text_BlogTitle = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int Text_Creator = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int Text_Loading = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int Text_WordType = 2131099653;
			
			// aapt resource value: 0x7f060000
			public const int WidgetBackground = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int widget_word = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
